-- Define game constants
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

PADDLE_WIDTH = 5
PADDLE_HEIGHT = 30

PADDLE_LEFT_X = VIRTUAL_WIDTH / 2 - 210
PADDLE_RIGHT_X = VIRTUAL_WIDTH / 2 + 205

PADDLE_LEFT_Y = VIRTUAL_HEIGHT / 2 - 50
PADDLE_RIGHT_Y = VIRTUAL_HEIGHT / 2 + 50

BORDER_PADDING = 2

BALL_X = VIRTUAL_WIDTH / 2
BALL_Y = VIRTUAL_HEIGHT / 2
BALL_RADIUS = 3

LEFT_SCORE_X = VIRTUAL_WIDTH - 360
RIGHT_SCORE_X = VIRTUAL_WIDTH + 330

PADDLE_SPEED = 200

BALL_VELOCITY_X = 0
BALL_VELOCITY_Y = 0